<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PN3ADTT" ignored="0" name="Test" tests="6" failures="2" timestamp="05 Jun 2019 02:20:36 GMT" time="0.048" errors="0">
  <testcase name="f" time="0.012" classname="Package1.TestClass1"/>
  <testcase name="f1" time="0.004" classname="Package1.TestClass1">
    <failure type="java.lang.AssertionError" message="this is failed">
      <![CDATA[java.lang.AssertionError: this is failed
at Package1.TestClass1.f1(TestClass1.java:18)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="0.004" classname="Package1.TestClass1"/>
  <testcase name="f" time="0.0" classname="Package1.TestClass2"/>
  <testcase name="f1" time="0.0" classname="Package1.TestClass2"/>
  <testcase name="f2" time="0.0" classname="Package1.TestClass2">
    <failure type="java.lang.AssertionError" message="this is failed in f2 of class2">
      <![CDATA[java.lang.AssertionError: this is failed in f2 of class2
at Package1.TestClass2.f2(TestClass2.java:24)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
</testsuite> <!-- Test -->
